# Copyright (c) 2022 Unately (Joshua Schmitt)
# 
# This software is released under the MIT License.
# https://opensource.org/licenses/MIT

name: Build Java Versions
on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * 1"
  push:
    branches:
      - master
    paths-ignore:
      - '.vscode/**'
      - 'LICENSE'
jobs:
  push:
    name: "java:${{ matrix.tag }}"
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        tag:
          - 17
    steps:
      - uses: actions/checkout@v2

      - uses: docker/setup-buildx-action@v1
        with:
          version: "v0.5.1"
          buildkitd-flags: --debug

      - uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - uses: docker/build-push-action@v2
        with:
          context: ./
          file: ./${{ matrix.tag }}/Dockerfile
          push: true
          tags: ghcr.io/upackages/java:${{ matrix.tag }}
          labels: ${{ steps.meta.outputs.labels }}
